### ISSUE TITLE
The bot stops after first process

### ISSUE THREAD

**Issue by demonicn1** [ProjectBots/StreamRaidersBot#10]
After loading the bot, it finds the first battles, and also place units, but when the timer expire, it doesn't load the next process.
It doesn't work for me since the Cyberfall event has ended.

**Comment by ProjectBots** [comment]
Sometimes it needs some time to find the next Raid that fits the settings you choose.
But to be safe:
Which Version do you use? (Maybe its a bug that is fixed on a newer version: current version 4.1.1)
Are there any Errors coming up in the console?
Does the timer stand still on 0 for more than 2 minutes?

**Comment by demonicn1** [comment]
The timer was still on 0 after 15-20minutes. I've also tried to delete, and re-add my profile, but it did the same before.
I had the 3.0.4 version, 44+ hours without any problem. It won't work since the Raid update.
I've tried the 4.1.2 version yet, and it's also stops after the first process. I got an error message -> Run->switchRaid: err=No captain matches
!
[raid](https://user-images.githubusercontent.com/18604380/116003466-5e760080-a5fe-11eb-9044-a42063819588.png)

**Comment by ProjectBots** [comment]
the error means that the bot cant find a raid which matches your config.
which chests have you blacklisted?
what is the max loyalty for normal chests?
what is the min loyalty for loyalty chests?

**Comment by demonicn1** [comment]
Every settings are the basic settings. Sometimes I've changed normal chests to gold, and loyalty chests to bronze, but thats all.
![raid2](https://user-images.githubusercontent.com/18604380/116004345-9b43f680-a602-11eb-89cc-556fdb09afe3.png)

**Comment by ProjectBots** [comment]
Something is really not going well and i cant recreate your error.
I published under the Release Site a new one named Debug.
Put the jar inside the bot folder (where the normal jar is too).
Then shift right click in the folder (not over a file).
=> Open PowerShell / Command prompt
type in: java -jar .\StreamRaidersBotDebug.jar
Hopefully the console will say something useful

in the meantime please check if you can play streamraiders in your browser

**Comment by demonicn1** [comment]
Streamraiders works fine in browser. I've recorded a video about debug.
www.youtube.com/watch?v=8tFz4bAFxUA

**Comment by ProjectBots** [comment]
I think we are coming closer to the error.
Updated the Debug release.
Same procedure to start

**Comment by ProjectBots** [comment]
updated again. the output will be automatically saved in a txt file (out.txt). it definitely includes user name and id

**Comment by demonicn1** [comment]
Thank you for fast response @ProjectBots ! I sent the debug to you in email.

**Comment by ProjectBots** [comment]
i think i fixed it (the bot thought it could use the 4th slot even though it couldnt) please try (is under the debug release).
you have to put the opt.app file in the data folder.

**Comment by demonicn1** [comment]
Tested it for 2hours+, looks like all fine now. I will test it more, I will contact you if I find any bug. Thank you for help! Keep up the good work!
