### ISSUE TITLE
Profile saving

### ISSUE THREAD

**Issue by rayzynx** [ProjectBots/StreamRaidersBot#15]
Everything works absolutely fine but it seems to never completely recognize / save my profile. None of the settings ever save and I need to log in again every time I boot it up. Am I doing something wrong or is this a bug?

**Comment by ProjectBots** [comment]
which bot version are you using?
Does any error pop up?
Can you please check after closing the bot whether something is written in the config file? (data/config.json)
Do you close the bot in any special way? (like killing the task with the taskmanager)

**Comment by rayzynx** [comment]
- 4.3.0 but it has been happening for a few versions now.
- No error pops up.
- I tried running it via power shell but nothing happens (and no error in powershell, just a quick flicker of some window opening and instantly closing)
- the config file is empty with only "{}" in it.
- i've tried both regular closing (clicking the windows "X" button) and via task manager but neither show any different results.

**Comment by ProjectBots** [comment]
is there a logs.app file in the main folder? if yes could you please share its content (its a text file)
Are you running windows or another os?
is java up to date? (powershell: java -version)

**Comment by rayzynx** [comment]
- There is no logs.app in the main or any of the folders
- java is up to date, i updated it to make sure and even did a fresh install (which i then checked again to make sure it is up to date. powershell returns no reply though so i used java's update checker)
- i do not use any special characters in the profile
- not sure what i'm reinstalling but i've downloaded a fresh copy of the bot if that's what you're asking

**Comment by ProjectBots** [comment]
I released a debug version
plese open with powershell and send the console output to creepimatze@gmail.com

**Comment by rayzynx** [comment]
I downloaded the debug version and tried booting it via powershell but nothing really opens. (java -jar .\StreamRaidersBot after shift+right clicking in the folder).

**Comment by ProjectBots** [comment]
not even the loading screen?

**Comment by rayzynx** [comment]
All I get is a very fast blink of a window, that's it. Tried using a full file path and a manually opened (and admin elevated) powershell window but it still didn't work.

**Comment by ProjectBots** [comment]
any error in the powershell window?

**Comment by rayzynx** [comment]
Nothing, just goes down a line.

**Comment by ProjectBots** [comment]
it only can be your java installation
try in powershell  java -XshowSettings:properties -version

**Comment by rayzynx** [comment]
Property settings:
    awt.toolkit = sun.awt.windows.WToolkit
    file.encoding = Cp1252
    file.encoding.pkg = sun.io
    file.separator = \
    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
    java.awt.printerjob = sun.awt.windows.WPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.endorsed.dirs = C:\Program Files\Java\jre1.8.0_291\lib\endorsed
    java.ext.dirs = C:\Program Files\Java\jre1.8.0_291\lib\ext
        C:\WINDOWS\Sun\Java\lib\ext
    java.home = C:\Program Files\Java\jre1.8.0_291
    java.io.tmpdir = C:\Users\user\AppData\Local\Temp\
    java.library.path = C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\WINDOWS\Sun\Java\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\Program Files (x86)\Razer Chroma SDK\bin
        C:\Program Files\Razer Chroma SDK\bin
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\dotnet\
        C:\Users\user\AppData\Local\Microsoft\WindowsApps
        .
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_291-b10
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_291
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.291-b10
    line.separator = \r \n
    os.arch = amd64
    os.name = Windows 10
    os.version = 10.0
    path.separator = ;
    sun.arch.data.model = 64
    sun.boot.class.path = C:\Program Files\Java\jre1.8.0_291\lib\resources.jar
        C:\Program Files\Java\jre1.8.0_291\lib\rt.jar
        C:\Program Files\Java\jre1.8.0_291\lib\sunrsasign.jar
        C:\Program Files\Java\jre1.8.0_291\lib\jsse.jar
        C:\Program Files\Java\jre1.8.0_291\lib\jce.jar
        C:\Program Files\Java\jre1.8.0_291\lib\charsets.jar
        C:\Program Files\Java\jre1.8.0_291\lib\jfr.jar
        C:\Program Files\Java\jre1.8.0_291\classes
    sun.boot.library.path = C:\Program Files\Java\jre1.8.0_291\bin
    sun.cpu.endian = little
    sun.cpu.isalist = amd64
    sun.desktop = windows
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = Cp1252
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level =
    sun.stderr.encoding = cp850
    sun.stdout.encoding = cp850
    user.country = US
    user.dir = C:\WINDOWS\system32
    user.home = C:\Users\user
    user.language = en
    user.name = user
    user.script =
    user.timezone =
    user.variant =

java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
PS C:\WINDOWS\system32>

**Comment by ProjectBots** [comment]
i updated the release
you have to click start.bat. (alternatively in powershell: .\jdk-16\bin\java.exe -jar .\StreamRaidersBot.jar)

**Comment by rayzynx** [comment]
I just wanted to update that besides a few unit placement errors (which didn't cause any major issues - this error displayed in both logs.app and in the command console window). The debug version is working fine and has saved the profiles properly. I have edited settings and it saved the changes and I did not need to relog into my account on twitch when rebooting the program.

**Comment by ProjectBots** [comment]
the only change to the normal version is that I added a Java version.
in other words: your java is not installed correctly.
please consider reinstalling your Java Runtime
(its probably the system variable which is not correct, i had a similar problem a few months ago)
