### ISSUE TITLE
Unable to locate executable file

### ISSUE THREAD

**Issue by williamski** [ProjectBots/StreamRaidersBot#16]
Hello and thank you for your work! From your Readme i could not identify the executable in this code? I am no expert and i am sorry to inconvenience you!

**Comment by ProjectBots** [comment]
its StreamRaidersBot.jar
you need to install java for this

**Comment by williamski** [comment]
Aaah i downloaded the wrong thing. Thank you for the reply, i feel stupid now :D

**Comment by ProjectBots** [comment]
no worries 😄
we are only humans 👍🏻
