### ISSUE TITLE
4.3.0 and 5.x.x debug build

### ISSUE THREAD

**Issue by Noa3** [ProjectBots/StreamRaidersBot#19]
my logins dont get saved and the bot is stopping working after some work(around 20 min?) with an error there are not enough cookies.

**Comment by ProjectBots** [comment]
When adding a profile, you’re supposed to let it load. Look into the inbuild guide under “add a profile” for more infos

**Comment by ProjectBots** [comment]
did the loading help to save the profiles?
The error with the bot getting stuck is discussed in #18

**Comment by Noa3** [comment]
The first Part i try again now with fully loading until streamer select. will report later if it worked.

For the Second problem: i get in the logs.app
this output, have for security reasons hidden my id:
---- 5:7,53 ----
Not enough cookies, got: scsession=*hidden*; _ga=GA1.2.1444996493.1620356856; _gid=GA1.2.1992937084.1620356856; 

started the debug build on your way now and if i get something, i will report

**Comment by ProjectBots** [comment]
The log file doesn’t reset. Are you sure you got this error from something else than adding a profile? The time stamp says that the error was created at 05:07

**Comment by ProjectBots** [comment]
the exception is very interresting. looks like a java method does not exist.
which java version do you use? (powershell: java -version)

**Comment by ProjectBots** [comment]
the exception is very interresting. looks like a java method does not exist.
which java version do you use? (powershell: java -version)
I added the the newest version of java to the debug release.
To run it hit start.bat or run "jdk-16\bin\java.exe -jar StreamRaidersBot.jar -debug" in powershell

**Comment by Noa3** [comment]
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by ProjectBots** [comment]
What does the debug version say?

**Comment by Noa3** [comment]
runing some time and then:

[Debug] claimQuests
[Debug] reloadStore
[Debug] store
[Debug] unlock
[Debug] upgradeUnits
[Debug] chests
reload srrh in 20 sec for *user*at 5:52
started reload for *user*
failed to reload srrh for *user*
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader java.net.URLClassLoader @378fd1ac)
        at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
        at program.SRR.constructor(SRR.java:102)
        at program.SRR.reload(SRR.java:95)
        at program.SRRHelper.reload(SRRHelper.java:47)
        at program.Run$3.run(Run.java:225)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

critical error happened for *user* at "chests" -> try to reload again
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonNull and com.google.gson.JsonArray are in unnamed module of loader java.net.URLClassLoader @378fd1ac)
        at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:182)
        at program.SRRHelper.updateRaids(SRRHelper.java:224)
        at program.SRRHelper.getRaids(SRRHelper.java:183)
        at program.Run.chests(Run.java:563)
        at program.Run.runs(Run.java:149)
        at program.Run$4.run(Run.java:289)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

reload srrh in 20 sec for *user* at 5:52

**Comment by ProjectBots** [comment]
I can now roughly say where the error is.. I updated the debug version. It should output the cause.
same way to start like before.
(tip you can copy the data/config.json into every 5.x.x release (same path). That way you dont have to login every time)

**Comment by Tjockas** [comment]
I'm having the same problem where it won't save my login.
Currently using Java: Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
And bot Version: 5.0.2debug
Haven't had any issues with the bot stopping though.

And haven't gotten any errors or logs so far (Using it for two days)

**Comment by ProjectBots** [comment]
did you start it via the start.bat or in powershell ( jdk-16\bin\java.exe -jar StreamRaidersBot.jar -debug ).
whats the output in the console?

**Comment by Tjockas** [comment]
> did you start it via the start.bat or in powershell ( jdk-16\bin\java.exe -jar StreamRaidersBot.jar -debug ).
> whats the output in the console?

I just tested with the newest version  that you uploaded this morning. It's working!
You can delete my previous post. Thanks for the update! Great work mate!

**Comment by ProjectBots** [comment]
yeah i tested it just a moment ago. The normal java runtime cant handle a method which is called while closing and saving the profiles even though it says that its compatible. Therefore until i found a workaround you have to start it via the start.bat or the powershell/cmd command and use the jdk-16, i packed with in, to start the bot correctly. But this solves only the problem with the profile saving, not the second error (which is probably a error from StreamRaiders, where i need the error msg to handle this right):

> 
> 
> runing some time and then:
> 
> [Debug] claimQuests
> [Debug] reloadStore
> [Debug] store
> [Debug] unlock
> [Debug] upgradeUnits
> [Debug] chests
> reload srrh in 20 sec for _user_at 5:52
> started reload for _user_
> failed to reload srrh for _user_
> java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader java.net.URLClassLoader @378fd1ac)
> at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
> at program.SRR.constructor(SRR.java:102)
> at program.SRR.reload(SRR.java:95)
> at program.SRRHelper.reload(SRRHelper.java:47)
> at program.Run$3.run(Run.java:225)
> at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> at java.base/java.util.TimerThread.run(Timer.java:506)
> 
> critical error happened for _user_ at "chests" -> try to reload again
> java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonNull and com.google.gson.JsonArray are in unnamed module of loader java.net.URLClassLoader @378fd1ac)
> at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:182)
> at program.SRRHelper.updateRaids(SRRHelper.java:224)
> at program.SRRHelper.getRaids(SRRHelper.java:183)
> at program.Run.chests(Run.java:563)
> at program.Run.runs(Run.java:149)
> at program.Run$4.run(Run.java:289)
> at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> at java.base/java.util.TimerThread.run(Timer.java:506)
> 
> reload srrh in 20 sec for _user_ at 5:52

**Comment by ProjectBots** [comment]
wait... i think i just recreated the error. @Noa3 Did you get the error directly when you click the run button?
if yes are you using firefox?

i think the problem is, that your firefox uses same user agent as the bot. I changed it and updated the debug release. You have to login again, but it should work if this was the problem. (start it via the powershell command or the start.bat)

**Comment by Noa3** [comment]
saving of the acounts is working now.

yeah i use all types of browsers on my pcs. Firefox,Opera,Chrome,Edge,Tor...because of work and testing.
the problem appears after a while running. currently with the latest debug build all is fine in the moment

**Comment by Noa3** [comment]
the bot is working now 24h without stopping and the acounts getting saved. so i think my problem is solved here for now. i have still some error output but this is not upgrade and random some other things.
thx @ProjectBots for working hard on this
