### ISSUE TITLE
Captains wich got Favoraited in the bot, dont get Played

### ISSUE THREAD

**Issue by Noa3** [ProjectBots/StreamRaidersBot#21]
if i give a captain a Pink Hearth in the Bot, it doesnt look if the streamer is on and fight for him.
or did i missunderstand it?

**Comment by ProjectBots** [comment]
The captain is prioritized if the bot switches a raid, but it also has to met the conditions of the profile config. If you want to force the bot to fight for a streamer, you have to lock the slot

**Comment by Noa3** [comment]
is it possible to check, if the actual fight are done > if a favorite streamer is on > change on him? not only if the streamer goes offline?
it would be more helpful i guess.

**Comment by ProjectBots** [comment]
I’ll add the options “change asap to ...”  and “search captain” (will give info if online) when I’m home.
Theoretically you can see if a fight is done when you open the map and no players are loaded.

**Comment by Noa3** [comment]
thank you much for this change, sadly i have only a bit experience in java and cant help with the projekt.
let your time, dont overwork and check if all is working fine.
