### ISSUE TITLE
Discord server invite seems to be down

### ISSUE THREAD

**Issue by jcmatoskx** [ProjectBots/StreamRaidersBot#22]
Also, I've been trying to run the project with Java but I haven't managed, any quick tips to go in the right direction? thank you!

**Comment by ProjectBots** [comment]
1. i fixed the discord link
2. do you get any error when trying to run? Did you tried the debug.bat?

**Comment by jcmatoskx** [comment]
I managed to get it to run using NetBeans! :) 
Should it need a third party tool like this to run the project? 

Thanks for the quick answer

**Comment by ProjectBots** [comment]
you should be able to run it with everything included in the release
