### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Trought0** [ProjectBots/StreamRaidersBot#23]
Hi there and thank you for your work! :)

I'm absolutely new here, so I don't know if this is the right place for suggestions.
I'll just shoot:

1. Placement of Epic Units
2. A different placement pattern
Don't get me wrong here. It is good! But might be too obvious.
3. Open Account in Browser
Like in the _New Profile_ window.
4. Shop priority
An option to prioritize/exclude certain scrolls 
5. A Start All next to the Skip All Button
6. Global profile settings

*Edit
Just found opt.app and will edit it to my needs in case of _6. Global profile settings_

**Comment by ProjectBots** [comment]
0. yes this is the right place for suggestion
1. the question is: under what circumstances should an epic unit be placed?
2. what placement pattern should I include or should I make it a bit more random? (at the moment: heatmap)
3. do you mean that you want to use the inbuild browser to play SR?
4. you can disable certain scrolls in the Unit settings (in the profile settings). The bot should make enough money to buy the whole store
5. already implemented in the preV6.0.0 (will be released in a few days)
6. what exactly do you mean? v6.0.0 will have a config export/import and copy functionality if it's what you mean
7. sorry for the late reply

**Comment by Trought0** [comment]
1. whenever possible and or certain captain(s) comes to my mind. Depending on the map could be another possobility but I think thats a bit overkill.
2. Well.. I have no idea how it works so.. :D Whatever _random_ means sounds better than just every unit next to eachother, although it might be good strategy wise. Near the captains unit could be another option.
3. Yes. Not really to play SR. Just to _check things_. Right now I would do this to choose a specific captain; check on / change skins; put down an Epic Unit.
4. My bad. Thats exactly it! :)
5. Wonderful!
6. Sound like you already implemented it. One _Profile Settings_ instead of having to change multiple ones to your needs.
7. ! ;)

**Comment by ProjectBots** [comment]
I put it on my TODO list, but i will first focus on the things im already working on

**Comment by Trought0** [comment]
Sounds great!
And thanks again for you awesome project! ;)
