### ISSUE TITLE
Critical Error with V6.0.0beta

### ISSUE THREAD

**Issue by Trought0** [ProjectBots/StreamRaidersBot#24]
![error](https://user-images.githubusercontent.com/84183575/118409395-7fc08e80-b68a-11eb-9543-d7184f5a6679.PNG)

This error appears when starting. (Single or All)
I copied the configs.jason from V5.1.1 to the V6 Beta. Might that be the problem?

**Comment by ProjectBots** [comment]
yes the configs are not compatible. you can solve this when you remove the favs array in the config itself or readd the profile

**Comment by Trought0** [comment]
Ok
So I have to add them again in V6?



Just so you know:
I tried deleting favs in the config.
Manual copying and importing of the configs.json so far.

When _importing_ the following errors pop up:
Configs -> conMerge: err=can't recognize key, key=chests
and
Configs -> conMerge: err=can't recognize key, key=units

So I deleted the chests, units and then the stats lines aswell. One after another.
I ended up with just the cookies lines per account. But then the Bot doesn't start anymore.

**Comment by ProjectBots** [comment]
it can only import an exported config because the config will be mapped when exporting.
with the cookies alone it should start.
have you tried a reinstall?

**Comment by Trought0** [comment]
I already tried it with a redownload. Did you change anything? It doesn't say so.
Redownloading right now.

> with the cookies alone it should start.
Do you mean I can import (paste) an config,json with just the login information?
What would be great.
{
"Account_1": {
    "cookies": "scsession\xxxxx; ACCESS_INFO\xxxxx",
    },
"Account_2": {
}

Like that?
Because that is what I tried after your first reply.

**Comment by ProjectBots** [comment]
if you got it from the old config then it should work (dont forget to remove the  ,  when theres no element after it in the brackets)
if its not working even after redownload and adding th profile again, please edit the debug.bat file and write in the first line:
jdk-16\bin\java.exe -jar StreamRaidersBot.jar -debug=out.txt all
and send me the logs.app file and the out.txt file to the email real.projectbots@gmail.com

**Comment by Trought0** [comment]
Ok Thanks!! I will try as soon as I downloaded the Files again.
GitHub seems to not like me downloading the same file a third time.
Got very low speed now. 1h+

**Comment by Trought0** [comment]
It is working now!

I pasted an edited configs,json into the newly downloaded folder and it's working just like you said ;)
Most likely I forgot to remove a **,** at the end of the 'cookies' line like I did in the example above.


Thank you very much for your patience! :)


Could have been something you changed in the files aswell (either or both).
> *Edit
> Added an Account V6.
> When starting I get:
> critical error happened for xxxxxx at "captains" -> skipped this round
> java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because the return value of "SameLink" is null

**Comment by ProjectBots** [comment]
no problem, always a pleasure helping others 👍🏻
