### ISSUE TITLE
Error When Running Bot

### ISSUE THREAD

**Issue by louio** [ProjectBots/StreamRaidersBot#25]
Everytime I try to run the bot I get this error:

> **Loui: Run _> setRunning
> java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because "uType" is null
> at program.Unit.(Unit.java:47)
> at program.SRRHelper.updateUnits(SRRHelper.java:280)
> at program.SRRHelper.(SRRHelper.java:33)
> at program.Run$2.run(Run.java:97)
> at java.base/java.lang.Thread.run(Thread.java:831)**

**Comment by VoxLight** [comment]
Could be you are trying to load a profile with corrupt Jason. Try resetting your profile.

Also, The bot is currently outdated. Dev is working to update it because the new Dungeons update has changed some things that break the bot.

**Comment by JoaoAlmirante** [comment]
I think the problem is if you have vampire lvl 1+ the bot just trow infinite erros.

**Comment by JoaoAlmirante** [comment]
> 
> 
> fixed with [v6.1.0](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.1.0beta)

Can you tell me how we not buying from shop? Just set the value to 0?

**Comment by ProjectBots** [comment]
set it to any negative number
