### ISSUE TITLE
Suggestions: Smart Unit Placement

### ISSUE THREAD

**Issue by VoxLight** [ProjectBots/StreamRaidersBot#27]
From what I have observed, the unit placement done by the bot blends in as a normal player when being done on larger streams. However, in some of the smaller streams, the bot tends to confine itself and clump its units together in an unnatural way. Also, the bot ignores any tile/map markings set by a captain.

I am not entirely sure what is or isn't possible, in terms of collecting information about the game. So if you can't see what tiles are, or where units are, then that's just that. But if you are able to obtain info on the map, then you could use a system to make the unit placement a bit smart. Both as a humanization technique, but also to make the bot more efficient. The following are just some thoughts on a system. It is most definitely not an optimized system and not the best. But might be at least an example.

0. If the # of units on a battlefield exceeds a user-defined limit (i.e. 25 for default), then any smart-unit placement can be ignored completely. This is because the time complexity of any method is linear to the number of units. So the more units there are, the longer it will take. Also, when there is a dense amount of units, then units placed by the bot blend in seamlessly.

1. After a unit is chosen to be placed, but before it is placed, there should be a check whether there are unit markings on the map. If there are unit markings, then only tiles with the unit marking of the chosen unit should be considered. If there are no unit markings, then any tile can be considered. I.e. if a ranged unit is going to be placed, then only tiles that the captain has marked for ranged units should be considered. If there are no available tiles of that unit type, then any non-"do not place" tiles can be considered instead.

- Also, it appears that there is some strange behavior from the bot when there is a low # of units. The bot tends to create an island of its own units that is very detrimental, in terms of gaining resources from the fight. The bot will place one unit in a corner, and then clump the rest of its units around that initial unit, even after more units have been added elsewhere on the map. Not sure if this is a bug because sometimes the bot will group up with all the other units correctly, but when there is a low number of units the bot tends to do the islanding behavior. You could have the bot always try and place units as close to the captain unit as it can. This seems to be what 90% of the player base does anyway, so it would look completely natural. The only issue being the bot will sometimes place units in places they normally wouldn't go. Such as a ranged/support unit in the front line, or a defender in the backline. You might want to add some special placement procedures for each type of unit, ranged/support/melee/defender in case there are no markings on the map for the bot to follow.
-

**Comment by ProjectBots** [comment]
Thats a lot of good Suggestions for a better placement.
Regarding map markings: The Bot first checks if there are map markings and searches if it has a Unit which fits the markings. This is done in the class Run, method findUnit(...). It is also considered in the pathfinding. ( in MapConv.asField(...) )
Regarding placing near other units: I will first try to rewrite the already existing Heatmap implementation to search after allies instead of enemies.
Regarding the strange behavior: that they group up might be a bug. I'll look into it. Up to now the bot tries to place at the nearest spot, with a bit randomnes, which has the highest heat/weight of enemies if not battle plan (markers) exists.

**Comment by VoxLight** [comment]
Thanks! It's clear that there are no issues with unit placement on larger streams. So this could be an edge case situation when there are low unit counts (such as when a battle first begins). It's normally rare for the bot to try and place units when there are no/low # of units on the field because of the time delay. 
If you want to try recreating this bug, then simply find a low pop streamer, wait for them to begin a brand new battle, and then skip time as soon as they start the battle so the only other unit is the captain unit or a few other units.

**Comment by ProjectBots** [comment]
should be fixed now
