### ISSUE TITLE
Epic Units

### ISSUE THREAD

**Issue by VoxLight** [ProjectBots/StreamRaidersBot#28]
I did some looking in the bot UI, and I couldn't find anything to enable/disable epic unit placement. The bot doesn't seem to do it, so I assume if it is a feature, it's also not on by default.

So, some suggestions for a feature request:

1. Would be an option to toggle on/off all epic unit placement.

2. Add priority to certain units to designate that you want that unit to become epic. This would be so that units we want to farm scrolls on won't be made into epics. The "use epic potions" could be added alongside the placement, upgrade, dupe, etc. values in the UI. 

3. If the current unit trying to be placed has the highest epic priority out of all units not currently on cooldown, then it will be made into an epic if points are available. Like the rest of the values, a negative value would disable that unit from being made into an epic. By default, all of the common units should be disabled to become epic and the other units should have the priority set to that rarities default placement priority value. This is to prevent only common units, such as archers/tanks from being the only unit to get epic. uncommon, rare, and legendary units are almost always on cooldown. So even if an epic unit is only a minute away, the common units getting placed will always be designated as the ones that should get epic. **This could be avoided if you also considered the epic priority level of all units with a cooldown under 5 minutes.**

**Comment by ProjectBots** [comment]
A Boolean value (can place as epic) would be easy to implement, but a priority system might be a bit more difficult. Should the bot prefer the epic prio value over the place prio if it has enough potions or a combination (sum for example) of the prio values?

**Comment by VoxLight** [comment]
The epic placement would only take place if a unit was going to be placed in the first place. So, after it is already decided which unit is going to be placed, then a check will be done. Every unit which is off cooldown will have their "epic placement" priority stat checked. If the unit which is about to be placed has the highest epic priority from all that have been tested, then we can place it as an epic if we have the potions to do so.

**Comment by ProjectBots** [comment]
That would cause the bot to only epic place the unit with the highest place and highest epic prio

**Comment by ProjectBots** [comment]
My idea would be: check potions, check which units are enabled for placing, switch the place value with the epic value, find unit (highest epic prio), place as epic

**Comment by VoxLight** [comment]
> That would cause the bot to only epic place the unit with the highest place and highest epic prio

You would only try epic placing after you have decided on which unit you want to place. Say a berserker is chosen as the next unit to be placed. Then the epic priority will come into effect. If a berserker is set to 30, but there is a legendary with 40 currently available to be placed, and we have enough potions to make an epic, then the berserker will just be placed as normal. This would continue until the unit which is trying to be placed is the unit with the highest epic priority. Since rares, epics, and legendaries are on cooldown for long periods of time, then when they are off cooldown, epic potions which are able to be made will be reserved for those by the design of this method. Disabling common/rare units from getting epic pots with -1 will also help to reserve potions for the epic and legendaries, since commons are almost always off cooldown, they will generally always use the epic potions.

**Comment by ProjectBots** [comment]
but isnt the point of a prio system to place the highest prio it can find and is placeable? like you want to epic place a common Unit, but not an rare Unit
