### ISSUE TITLE
6.2.3 beta - dungeons setting is confusing

### ISSUE THREAD

**Issue by AshleyPinner** [ProjectBots/StreamRaidersBot#29]
Since upgrading to 6.2.3 I can't get the bot to play dungeons properly.

The challenge is also compounded by the UI not being instinctive:
![image](https://user-images.githubusercontent.com/6331215/120637790-3bddcf80-c467-11eb-9e1c-90143fb7b8db.png)

The black entries are the standard battles, the blue is the dungeon slot. The settings UI asks this:
![image](https://user-images.githubusercontent.com/6331215/120637885-5adc6180-c467-11eb-87c7-e833ded0eb82.png)

On the actual SR site, blue is the leftmost slot, so there's no correlation between slot layouts on the site and slots layouts in the UI.

Can we get slot numbering on the main UI? I don't mind if they're zero-starting (arrays start at zero, makes sense to me, but might not be newbie friendly!), but it would be handy to have some idea as to which slot is zero, one, etc.

No matter what slot number I select, the bot does not place any units in the flight, even if I have ones ready that match the planning squares. Collection of the chest happens if I play the dungeon for the bot, but that sorta defeats the point of the bot 😄

**Comment by ProjectBots** [comment]
its the slot layout from SR because it follows the UserSortIndex variable. 
the UI from the main frame follows no direct layout, just display what comes first.
But in your case: You locked the slots, therefore the bot cant switch what is in the slots. even though it does not like where the dungeon raid is, it cant switch it
by the way, slot 3 is only available with the battle pass from SR (0 to 3, left to right in SR)

**Comment by VoxLight** [comment]
Slots 0 1 2 refer to the slots in the game. They don't mean the slots displayed in the UI. Perhaps this could be made into suggestions so that the bot UI displays the same order as in the game.

**Comment by AshleyPinner** [comment]
>  it does not like to place for dungeons if its not a dungeon slot.

I mean, can't it work that out from what the reward chest is? Why do I need to tell it something it can/might be able to derive?

But yes, as VoxLight has said above, being able to work out which slot is which on the bot UI would be handy.

**Comment by ProjectBots** [comment]
Matching the UI with SR is on my TODO list
