### ISSUE TITLE
critical error Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive

### ISSUE THREAD

**Issue by lchavas** [ProjectBots/StreamRaidersBot#30]
Hi, 

The newest version 6.2.4 beta works for a few hours, then produces the following error :

`---- 14:9,49 ----
critical error happened for DND35 at "DND35 captains" -> skipped this round
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
	at program.Configs.getChestBoolean(Configs.java:192)
	at program.Run.captains(Run.java:806)
	at program.Run.runs(Run.java:174)
	at program.Run$4.run(Run.java:329)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)`

I have gold and silver chests disabled in profile config. Maybe it happens if it finds no suitable captains ?

Best regards,
Lewis

**Comment by lchavas** [comment]
![image](https://user-images.githubusercontent.com/12186432/120799465-115f4580-c53f-11eb-89ec-5517d600876d.png)

**Comment by ProjectBots** [comment]
fixed in [v6.2.5beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.2.5beta)

**Comment by lchavas** [comment]
Damn a new version 2 minutes later.
You work fast ;)

**Comment by ProjectBots** [comment]
your were not the only one complaining

**Comment by lchavas** [comment]
Thank you for your hard work!
