### ISSUE TITLE
Separate timer for dungeon checks

### ISSUE THREAD

**Issue by wesh30** [ProjectBots/StreamRaidersBot#31]
Should add a separate timer for dungeons or does the bot internally handle the faster deploying for dungeons?

**Comment by ProjectBots** [comment]
as far as i know, dungeons ends in a few days and because of the way the Bot is programmed it would be very difficult to implement this. 
I keep this in mind in the case dungeons comes up more often in the future

**Comment by ProjectBots** [comment]
implemented in [v7.1.1](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v7.1.1beta)
