### ISSUE TITLE
Idea: 'maximum time left before battle is ready' setting

### ISSUE THREAD

**Issue by lchavas** [ProjectBots/StreamRaidersBot#36]
Hi,

First of all, great work on this program. Very efficient and has become very stable lately.

I submit to you an improvement idea:
In order to cycle through victories faster, would it be possible to specify the max remaining time before battle is ready allowed in order to join a game ?

**Comment by ProjectBots** [comment]
Put it on my todo list

**Comment by ProjectBots** [comment]
implemented in [v7.1.1](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v7.1.1beta)
