### ISSUE TITLE
"Buy dungeon chests" option not working in Dungeons 2

### ISSUE THREAD

**Issue by lchavas** [ProjectBots/StreamRaidersBot#37]
The "buy dungeons chests" option does not seem to work for my profile. Can you confirm or is the problem on my side ?

Best regards.

**Comment by rayzynx** [comment]
> 
> 
> The "buy dungeons chests" option does not seem to work for my profile. Can you confirm or is the problem on my side ?
> 
> Best regards.

It's not just you. Since the launch of Dungeons 2 the option hasn't worked for me either.

**Comment by ProjectBots** [comment]
fixxed in [v6.3.5](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.5beta)
