### ISSUE TITLE
Import seems to be broken

### ISSUE THREAD

**Issue by derpyderpaderp** [ProjectBots/StreamRaidersBot#39]
I export my profile from an older version and for some reason it will not import when I try and import it to a new version of the bot. This worked 2-3 versions ago but I have been having to reset it manually since then. Is their a possible way of fixing this or maybe an easier way of understanding the steps? Because it seems like I do it one time and it works and the next time it won't.

**Comment by ProjectBots** [comment]
does the profile name has a name (or a is it blank?)
can you hide the cookie value in the exported json and post it here?

**Comment by derpyderpaderp** [comment]
The Json file is empty for some reason.

**Comment by derpyderpaderp** [comment]
Hmm just did the same steps I did before and now that json file has something in it... Not sure what or If I did anything different.

**Comment by ProjectBots** [comment]
did you checked at leasst one of your profile(s)

**Comment by derpyderpaderp** [comment]
even with text being in json when I import it does nothing besides leave a blank screen.

**Comment by ProjectBots** [comment]
can you hide the value of "cookies" and post the json in here?

**Comment by derpyderpaderp** [comment]
> did you checked at least one of your profile(s) while exporting?
is their supposed to be a name where it says profiles?

**Comment by ProjectBots** [comment]
![grafik](https://user-images.githubusercontent.com/44307196/125000729-54866a00-e051-11eb-9536-382304d0cd46.png)

**Comment by derpyderpaderp** [comment]
Weird I don't have profiles under there and I even make sure to make a name for each profile when I have to redo the setup. Here is the JSON file to see if their is anything there maybe. 
[test.txt](https://github.com/ProjectBots/StreamRaidersBot/files/6787717/test.txt)
 PS had to change it to txt because github doesn't allow JSON

**Comment by ProjectBots** [comment]
if there is no name you have to close the bot. open data/configs.json
and put sth in here:
![grafik](https://user-images.githubusercontent.com/44307196/125001054-09b92200-e052-11eb-8814-9871f8de87ff.png)

and make sure to give the profile a name when importing:
![grafik](https://user-images.githubusercontent.com/44307196/125001117-353c0c80-e052-11eb-8e08-f40bcca21a8d.png)

**Comment by derpyderpaderp** [comment]
Also not sure if this helps but the only thing there and I have it selected is profiles
![C2lFxMJ](https://user-images.githubusercontent.com/12119604/125001198-b1652e80-e017-11eb-8d30-7c5135cd9d87.png)

**Comment by ProjectBots** [comment]
> 
> 
> if there is no name you have to close the bot. open data/configs.json
> and put sth in here:
> ![grafik](https://user-images.githubusercontent.com/44307196/125001054-09b92200-e052-11eb-8814-9871f8de87ff.png)
> 
> and make sure to give the profile a name when importing:
> ![grafik](https://user-images.githubusercontent.com/44307196/125001117-353c0c80-e052-11eb-8e08-f40bcca21a8d.png)

did you do these steps?

**Comment by derpyderpaderp** [comment]
> > if there is no name you have to close the bot. open data/configs.json
> > and put sth in here:
> > ![grafik](https://user-images.githubusercontent.com/44307196/125001054-09b92200-e052-11eb-8814-9871f8de87ff.png)
> > and make sure to give the profile a name when importing:
> > ![grafik](https://user-images.githubusercontent.com/44307196/125001117-353c0c80-e052-11eb-8e08-f40bcca21a8d.png)
> 
> did you do these steps?
Okay this worked. Not sure why it wasn't giving itself a name originally. I might be doing something wrong here.
