### ISSUE TITLE
add entity error

### ISSUE THREAD

**Issue by mystixa** [ProjectBots/StreamRaidersBot#45]
Have developed an error today, I think with the new event.

It pops up in the log as 'map_>addentity:team = neutral ' 

running 6.3.15

I don't see a place within the event to add a team. Sorry if I've missed a detail that I need to set now.

**Comment by DylanSimowitz** [comment]
Try the new release https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.16beta

**Comment by mystixa** [comment]
it looks like this may be addressed with the 6.3.16 version. I didn't download that one at first since it said it was a 'debug version', but its being posted as the solution in the Discord. Giving it a try now.

**Comment by mystixa** [comment]
> Try the new release https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.16beta

yup that looks like the solution. Thanks for the quick reply btw. :)
