### ISSUE TITLE
Error - ***: Run -> setRunning

### ISSUE THREAD

**Issue by Vttic** [ProjectBots/StreamRaidersBot#47]
Hello,

From this morning the bot is not working anymore. I try to add a new profile, but same issue... Any clue for this one ?
Here is the log I got :

[Debug] added scope general
[Debug] added scope run
[Debug] added scope runerr
[Debug] added scope lowerr
[Debug] added scope loop
[Debug] added scope srerr

[info] [8:18:47] [general] started

[fatal] [8:23:19] [runerr] ***: Run -> setRunning
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because "uType" is null
	at program.Unit.<init>(Unit.java:55)
	at program.SRRHelper.updateUnits(SRRHelper.java:361)
	at program.SRRHelper.<init>(SRRHelper.java:37)
	at program.Run$2.run(Run.java:112)
	at java.base/java.lang.Thread.run(Thread.java:831)

[info] [8:23:24] [general] System exit

**Comment by ProjectBots** [comment]
fixed in [v6.3.18beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.18beta)

**Comment by Vttic** [comment]
Yes it is working ! Sorry for that, I didn't see the new version coming !
