### ISSUE TITLE
No Captain Matches

### ISSUE THREAD

**Issue by VoxLight** [ProjectBots/StreamRaidersBot#48]
![image](https://user-images.githubusercontent.com/26353962/135576176-a01a4ef8-1b83-46d2-af06-b384f100ca10.png)

Just appears randomly while the bot is running.

Logs.txt
[logs.txt](https://github.com/ProjectBots/StreamRaidersBot/files/7264735/logs.txt)

**Comment by ProjectBots** [comment]
Try setting the dungeon slot to none
