### ISSUE TITLE
New error starting today

### ISSUE THREAD

**Issue by korytyler21** [ProjectBots/StreamRaidersBot#49]
Just posting a log of what appears to be a map load error that prevents the bot from running
[2021-10-20_22-20-03.txt](https://github.com/ProjectBots/StreamRaidersBot/files/7385522/2021-10-20_22-20-03.txt)

**Comment by Vttic** [comment]
Same issue here, with v6.3.21

**Comment by ProjectBots** [comment]
fixed in [v6.3.22beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.22beta)

**Comment by ProjectBots** [comment]
https://www.dropbox.com/s/6bzdk4y7sxjjy8w/StreamRaidersBot.zip?dl=0
heres the complete current source code.
i wanted to see how much changes from v6.3.x to v7.0.0 and therefore didnt pushed the commits
