### ISSUE TITLE
Unable to unlock unit

### ISSUE THREAD

**Issue by wfzelle** [ProjectBots/StreamRaidersBot#51]
Getting 'Unable to unlock unit' errors on each run for Additional Units that can be upgraded. The bot does work otherwise, but the errors are really irritating. Can you please fix it?

**Comment by ProjectBots** [comment]
will be fixed with next update

**Comment by ProjectBots** [comment]
fixed in [v6.3.25beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.25beta)
