### ISSUE TITLE
err message about on 6.5.3

### ISSUE THREAD

**Issue by mystixa** [ProjectBots/StreamRaidersBot#54]
Hii .. I started having this error in the version before.. now upgraded to 6.5.3. 

From the log:
[error] [2:8:27] [runerr] [mystixa] Run -> captains: err=No Captain Matches
program.Run$NoCapMatchException: No Captain Matches
	at program.Run.getCaps(Run.java:980)
	at program.Run.getCaps(Run.java:970)
	at program.Run.captains(Run.java:923)
	at program.Run.runs(Run.java:182)
	at program.Run$4.run(Run.java:337)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
	
	
	I tried minimal upgrade at first. Then deleted it all and put in full 6.5.3. Relogged in to try that.

**Comment by ProjectBots** [comment]
1. check if you still have a dungeon slot enabled (dungeon is over)
2. StreamRaiders currently has a lot of problems with the captain search (probably bcs Twitch is changing stuff in their API)

**Comment by mystixa** [comment]
![srd](https://user-images.githubusercontent.com/13580903/153696569-3aa2d237-a045-4748-a6e2-b9d8c33f63f6.png)
oo yea must be a combo of those things. Thank you for the reply. I am still running dungeons.. but I still have 14 hours left .. just took the above pic a moment ago. I'll know to drop it quickly at the end though to avoid further errors.
