### ISSUE TITLE
7.1.1 is not working for me

### ISSUE THREAD

**Issue by wfzelle** [ProjectBots/StreamRaidersBot#55]
Getting just a fully white page when starting it. Tried both the update and the full version. This version creates a configsV2.json file next to the old one. Perhaps that has something to do with the problem?

**Comment by ProjectBots** [comment]
Because of the many changes in the config, you need to export your old one and import it into V7.

**Comment by wfzelle** [comment]
I had to log into Twitch again. Now it's working. Importing didn't really work, but that's not too bad. I don't see how to disable buying from the store anymore, though.
