### ISSUE TITLE
So many unexplained options

### ISSUE THREAD

**Issue by Rynerak** [ProjectBots/StreamRaidersBot#62]
In the "Units" panel their is a list of options labelled "markerOnly", how does that work? is it related to only placing units in the correct markers designated by the captain? as this is something I'd like.
Is there also plans to allow the bot to function in PvP matches?

**Comment by ProjectBots** [comment]
If enabled it will only place the unit on markers
NC= Normal campaign
ND= Normal dungeon
EC= Epics campaign (when placing epic)
ED= Epic dungeons (When placing an epic in dungeons)

But currently markers are broken bcs of the last sr update. I am already working on the fix.

There are plans for PvP, but I am not working on it atm.
