### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Githubuser121212** [ProjectBots/StreamRaidersBot#69]
Bot worked until a month ago, not working now

**Comment by ProjectBots** [comment]
Can you please describe your issue with more details

**Comment by Githubuser121212** [comment]
Changes captains, but will not place units at all anymore

**Comment by ProjectBots** [comment]
can you test if the error persists in the latest release

**Comment by VaanC** [comment]
Sometimes bot wont place units for no reason, sometimes place on all 3(4) slots and sometimes work only on 1 or 2 slots. 
Restarting bot or changing the captain didn't help.

**Comment by Githubuser121212** [comment]
It seems to work a bit now. Thank you for the fix. 

It isn't perfect, but helps to farm a bit. ^_^

**Comment by derpyderpaderp** [comment]
> Sometimes bot wont place units for no reason, sometimes place on all 3(4) slots and sometimes work only on 1 or 2 slots. 
> Restarting bot or changing the captain didn't help. 7.3.2beta
> Otherwise great job. 

Same issue. Noticed it does this when markers are used. Specifically the peace sign marker.

**Comment by Githubuser121212** [comment]
Some is better than none
