### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [ProjectBots/StreamRaidersBot#71]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/ProjectBots/StreamRaidersBot/blob/cd3e199106976cc36f9c2c308a5af6ad081f713a/StreamRaidersBot/GraphicalUserInterface/src/userInterface/VIEWER/ProfileSettings.java

**Comment by ProjectBots** [comment]
?????
