### ISSUE TITLE
Refusing to place on all slots?!

### ISSUE THREAD

**Issue by derpyderpaderp** [ProjectBots/StreamRaidersBot#75]
All it says when trying to place on 3rd slot is "BackEnd -> testUpdate: err=Error retrieving captains, jo={"info":{"version":"0.207.1","dataPath":"https://streamcap-prod1.s3.amazonaws.com/data/data.f2c6701fc865.json","dataVersion":"f2c6701fc865","serverTime":"2022-10-27 03:37:06","clientVersion":"0.46.4"},"status":"error","data":null,"errorMessage":"Error retrieving captains"}" This is on version 7.4.4 beta.

EDIT: CORRECTION It is happening on all slots

**Comment by jwchia1** [comment]
> All it says when trying to place on 3rd slot is "BackEnd -> testUpdate: err=Error retrieving captains, jo={"info":{"version":"0.207.1","dataPath":"[https://streamcap-prod1.s3.amazonaws.com/data/data.f2c6701fc865.json","dataVersion":"f2c6701fc865","serverTime":"2022-10-27](https://streamcap-prod1.s3.amazonaws.com/data/data.f2c6701fc865.json%22,%22dataVersion%22:%22f2c6701fc865%22,%22serverTime%22:%222022-10-27) 03:37:06","clientVersion":"0.46.4"},"status":"error","data":null,"errorMessage":"Error retrieving captains"}" This is on version 7.4.4 beta.
> 
> EDIT: CORRECTION It is happening on all slots

exact same thing is happening to mine

**Comment by ProjectBots** [comment]
should be fixed now
